name: Notify WhatsApp Group on GitHub Push

on:
  push:
    branches:
      - main 

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send WhatsApp Notification
        env:
          WHATSAPP_API_KEY: ${{ secrets.WHATSAPP_API_KEY }}
          WHATSAPP_GROUP_ID: ${{ secrets.WHATSAPP_GROUP_ID }}
        run: |
          curl -X POST "https://api.whatsapp.com/send" \
          -H "Authorization: Bearer $WHATSAPP_API_KEY" \
          -d "{
            \"to\": \"$WHATSAPP_GROUP_ID\",
            \"message\": \"🚀 Push terbaru di repo ${GITHUB_REPOSITORY}! Cek perubahan: https://github.com/${GITHUB_REPOSITORY}/commits/main\"
          }"
