name: Notify WhatsApp Contacts on GitHub Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send WhatsApp Notifications via Twilio
        env:
          TWILIO_ACCOUNT_SID: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN: ${{ secrets.TWILIO_AUTH_TOKEN }}
          WHATSAPP_PHONE_1: ${{ secrets.WHATSAPP_PHONE_1 }}
          WHATSAPP_PHONE_2: ${{ secrets.WHATSAPP_PHONE_2 }}
          WHATSAPP_PHONE_3: ${{ secrets.WHATSAPP_PHONE_3 }}
          WHATSAPP_PHONE_4: ${{ secrets.WHATSAPP_PHONE_4 }}
          WHATSAPP_PHONE_5: ${{ secrets.WHATSAPP_PHONE_5 }}
        run: |
          NUMBERS=("${{ secrets.WHATSAPP_PHONE_1 }}" "${{ secrets.WHATSAPP_PHONE_2 }}" "${{ secrets.WHATSAPP_PHONE_3 }}" "${{ secrets.WHATSAPP_PHONE_4 }}" "${{ secrets.WHATSAPP_PHONE_5 }}")
          
          MESSAGE="🚀 GitHub Push Alert!\n👤 User: ${{ github.actor }}\n📜 Commit: ${{ github.event.head_commit.message }}\n⏰ Time: ${{ github.event.head_commit.timestamp }}\n🔗 Repo: https://github.com/${{ github.repository }}/commits/main"

          for NUMBER in "${NUMBERS[@]}"; do
            curl -X POST "https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json" \
            --data-urlencode "From=whatsapp:+14155238886" \
            --data-urlencode "To=$NUMBER" \
            --data-urlencode "Body=$MESSAGE" \
            -u "${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }}"
          done
